### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by rstmsn** [delight-im/PHP-Router#3]
Getting an internal server error when attempting to access mydomain.com/test route.
The mydomain.com/ route loads successfully.

Here's index.php:

`<?php

	require __DIR__ . '/../vendor/autoload.php';

	$router = new \Delight\Router\Router();

	$router->get('/', function () {
    	echo 'howdy !';
	});

	$router->get('/test', function () {
    	echo 'test !';
	});`

.htaccess is configured according to the instructions, as follows:

`RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule . index.php [L]`

**Comment by rstmsn** [comment]
Looks like the .htaccess example provided required a leading '/' in front of the 'index.php'.

**Comment by ocram** [comment]
This is not what we have experienced so far, but thanks for letting us know. Perhaps your Apache configuration or virtual host configuration is different in a way that affects this. Apart from that, checking the Apache error logs would probably have been helpful.
